# Generated by Django 3.0.7 on 2020-06-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_key',
            field=models.CharField(blank=True, default='fq1eum', editable=False, max_length=6),
        ),
    ]
