# Generated by Django 3.0.7 on 2020-06-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200624_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_key',
            field=models.CharField(blank=True, default='zegjs1', editable=False, max_length=6),
        ),
    ]
