# Generated by Django 3.0.7 on 2020-06-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200625_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_key',
            field=models.CharField(blank=True, default='2t5scn', editable=False, max_length=6),
        ),
    ]
